CREATE OR REPLACE FUNCTION UPDATE_ORDER_PRICES(PERCENTAGE DECIMAL) 
RETURNS TABLE("BookTitle" VARCHAR, "Price" DECIMAL)
LANGUAGE PLPGSQL AS 
$$
BEGIN
   UPDATE bookstore SET price = PERCENTAGE * price;
   RETURN QUERY SELECT booktitle, price FROM bookstore;
END;
$$;